version: '3'

services:

  webapp:
    build: ./webapp

    environment:
      - NODE_ENV=production

    ports:
      - '5000:5000'

    volumes: 
      - ./webapp/uploads:/app/uploads
      - ./webapp/api:/app/api
      - ./webapp/client:/app/client